package ws.client;

import javax.jws.soap.SOAPBinding;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient
@SOAPBinding(style = SOAPBinding.Style.RPC)

public class BankPayImplService
        extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName BANKPAYSIMPLSERVICE = new QName("http://tempuri.org/", "IServer1Cservice");
    private final static QName BANKPAYSIMPLPORT = new QName("http://tempuri.org/", "IServer1CPort");

    static {
        URL url = null;
        try {
            url = new URL("http://172.22.223.210:8083/wsdl/IServer1C?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BankPayImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankPayImplService() {
        /*
        super(BankPayImplService_WSDL_LOCATION,
                new QName("http://client.ws/", "BankPayImplService"));
        */
        super(WSDL_LOCATION, BANKPAYSIMPLSERVICE);
    }

    /**
     *
     * @return
     *     returns BankPayI
     */
    @WebEndpoint(name = "BankPayImplPort")
    public BankPay getBankPayImplPort() {
        return (BankPay)super.getPort(
                BANKPAYSIMPLPORT,
                BankPay.class);
    }

    /**
     *
     * @param features
     *  A list of {@link WebServiceFeature} to configure on the proxy.
     *  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *  returns BankPayI
     */
    @WebEndpoint(name = "BankPayImplPort")
    public BankPay getBankPayImplPort(WebServiceFeature... features) {
        return (BankPay)super.getPort(
                BANKPAYSIMPLPORT,
                BankPay.class,
                features);
    }




}


